namespace Q10.StudentManagement.Domain.RegistrationSubject.Queries.GetManyByFilters;

public record GetManyByFiltersRegistrationSubjectQueryResponse(IEnumerable<RegistrationSubject> RegistrationSubjects);