namespace Q10.StudentManagement.Application.RegistrationSubject.Queries.GetManyByFilters;

public record AppGetManyByFiltersRegistrationSubjectQueryResponse(IEnumerable<Domain.RegistrationSubject.RegistrationSubject> RegistrationSubjects);